apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Test-api
  namespace: staging
spec:
  selector:
    matchLabels:
      app: Test-api
  replicas: 1
  template:
    metadata:
      labels:
        app: Test-api
    spec:
      containers:
      - image: 949725605288.dkr.ecr.us-east-1.amazonaws.com/producao:v2
        name: Test-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: Test-api
  namespace: staging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: Test-api
